#!/bin/bash

#one command line argument filepath to test set file

#if no argment in test set file, print usage message
if [ $# -eq 0 ]; then
    echo "Usage: $0 filepath" >&2 
    exit 
fi

#iterate through contents of test set file
#for each argument "stem" in test set
for stem in $(cat $1); do
    #if stem.desc dne, print message
    if [ ! -e $stem.desc ]; then
        echo "$stem No test description"
    #if stem.desc exists, print contents
    else
        cat $stem.desc
    fi
done

